name = "agri-sense"
main = ".output/server/index.mjs"
compatibility_date = "2025-07-15"
assets = { directory = ".output/public/", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "agrisense-db"
database_id = "56e10fb0-6b3a-46fe-a263-bedce8f48382"

[vars]
JWT_SECRET = "agrisense-super-secret-session-key-2026-min32chars!"